### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [cakctus/portfolio-template#1]
медизапрос к высоте рассчитан плохо, происходит перескакивание размера
![image](https://user-images.githubusercontent.com/8464662/185394839-23eab1ea-640f-4e5e-bc1b-366a7da3ad17.png)

**Comment by cakctus** [comment]
Исправил

**Comment by Alecto** [comment]
Для сдачи проекта требуются две ссылки:
1 - на страницу github pages.
2 - на страницу репозитория.
Все описание есть в документации, в разделе "Критерии сдачи проекта".


чт, 18 серп. 2022 р. о 17:30 cakctus ***@***.***> пише:

**Comment by cakctus** [comment]
https://github.com/cakctus/portfolio-template
https://cakctus.github.io/portfolio-template/

чт, 18 авг. 2022 г. в 17:35, Andrey ***@***.***>:

**Comment by Alecto** [comment]
отлично, теперь имя, фамилия группы - в гитхаб этой информации нет

чт, 18 серп. 2022 р. о 17:36 cakctus ***@***.***> пише:
